//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCmpApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessCmpDbEntities : DbContext
    {
        public BusinessCmpDbEntities()
            : base("name=BusinessCmpDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmplpoyeeDetail> EmplpoyeeDetails { get; set; }
        public virtual DbSet<ProjectManager> ProjectManagers { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<vManagerDetail> vManagerDetails { get; set; }
        public virtual DbSet<vProjectEmployeeDetail> vProjectEmployeeDetails { get; set; }
    }
}
